[workspace]
channels = ["conda-forge", "pytorch"]
name = "print-tune"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
streamlit = ">=1.52.2,<2"
pillow = ">=12.0.0,<13"
numpy = ">=2.4.0,<3"
pytorch = ">=2.9.1,<3"
gpytorch = ">=1.14.3,<2"
botorch = ">=0.16.1,<0.17"

[pypi-dependencies]
printtune = { path = ".", editable = true }
